### ISSUE TITLE
Gauge Chart

### ISSUE THREAD

**Issue by C2RT** [m8r1us/Tier0Hound#1]
Really cool but the Gauge Charts don't works. As example this statement show the follow error:

MATCH (c:Computer)-[:HasSession]->()
WITH COUNT(DISTINCT(c)) as computersWithSessions
MATCH (c2:Computer)
RETURN toInteger(100 * (toFloat(computersWithSessions) / COUNT(c2))) as PercentComputersWithSessions

Error:
*******************************************
Aggregation column contains implicit grouping expressions. For example, in 'RETURN n.a, n.a + n.b + count(*)' the aggregation expression 'n.a + n.b + count(*)' includes the implicit grouping key 'n.b'. It may be possible to rewrite the query by extracting these grouping/aggregation expressions into a preceding WITH clause. Illegal expression(s): computersWithSessions (line 4, column 33 (offset: 138))
"RETURN toInteger(100 * (toFloat(computersWithSessions) / COUNT(c2))) as PercentComputersWithSessions"
                                 ^

Any idea? - by the way - non of the Gauge Charts work in my chase.

**Comment by m8r1us** [comment]
Hey C2RT

I just tested the dashboard and it worked. 

Perhaps you can elaborate on your setup.
- Are you using Neo4j Desktop with the NeoDash application?
- Are you getting this error in the Neo4j browser or in NeoDash?
- Have you imported the BloodHound data? / Do you have computer nodes?
- Windows or Linux?
- Did you import the JSON file? (Dashboard -> Import) 

The query itself is correct - maybe you copied it and it has some special characters / line breaks in it?
Anyway I made the cypher a bit nicer, but the result should be the same:
```
MATCH (c:Computer)
WITH COUNT(c) as totalComputers
MATCH (c2:Computer)-[:HasSession]->()
WITH COUNT(DISTINCT(c2)) as computersWithSessions, totalComputers
RETURN toInteger(100 * (toFloat(computersWithSessions) / totalComputers)) as PercentComputersWithSessions
```

**Comment by C2RT** [comment]
Hi m8r1us,

thanks a lot for your feedback.

- I'm using Neo4j Desktop (Version 1.5.9), DBMS Version 5.20.0 with NeoDash 2.4.8
- i get the error in NeoDash
- BloodHound data are imported
- i use Windows
- yes, JSON fie is imported

The new query, nicer query works fine with this versions. May it's possible to change all gauge chart queries because no of the charts works? Microsoft Copilot rewrite the queries and "correct" the error in the queires but i can't evaluate if the result now is still correct. :-)

**Comment by m8r1us** [comment]
I think the problem is the neo4j dbms version you are using. For BloodHound you should be using the latest Neo4j 4.4.x not 5.x. Can you try to downgrade the DB version or create a new DB in neo4j Desktop? For the 4.4.x DB version, you will need to re-download the GDS and APOC plugins. (See for the version supportability: https://bloodhound.readthedocs.io/en/latest/installation/windows.html#install-neo4j)

But thanks for letting me know. I will update the queries for the next release, then they will work for 5.0 as well.

**Comment by C2RT** [comment]
Thank you for your feedback. With DBMS version 4.4.x all charts works fine.
